"""add_corrections_and_is_voided

Revision ID: 292d31de9e2d
Revises: d17d5aa61c72
Create Date: 2026-07-10 01:26:25.021656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '292d31de9e2d'
down_revision: Union[str, None] = 'd17d5aa61c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corrections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.BigInteger(), nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=True),
    sa.Column('correction_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('site_name', sa.String(length=100), nullable=True),
    sa.Column('process', sa.String(length=100), nullable=True),
    sa.Column('shift_type', sa.String(length=10), nullable=True),
    sa.Column('requested_checkin_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_checkout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_checkout_fix', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['work_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('work_records', sa.Column('is_voided', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_records', 'is_voided')
    op.drop_table('corrections')
    # ### end Alembic commands ###
