"""init

Revision ID: 9614d542c65d
Revises: 
Create Date: 2026-06-26 22:52:04.455608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9614d542c65d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_action', 'audit_logs', ['created_at', 'action'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workers_active', 'workers', ['id'], unique=False, postgresql_where=sa.text('is_active = TRUE'))
    op.create_index('uq_worker_company_phone', 'workers', ['company', 'phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL'))
    op.create_table('work_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.BigInteger(), nullable=False),
    sa.Column('process', sa.String(length=100), nullable=False),
    sa.Column('checkin_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checkout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), sa.Computed('(EXTRACT(EPOCH FROM (checkout_at - checkin_at))::int / 60)::int', persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_work_records_worker_checkin', 'work_records', ['worker_id', 'checkin_at'], unique=False)
    op.create_index('uq_active_checkin', 'work_records', ['worker_id'], unique=True, postgresql_where=sa.text('checkout_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_checkin', table_name='work_records', postgresql_where=sa.text('checkout_at IS NULL'))
    op.drop_index('ix_work_records_worker_checkin', table_name='work_records')
    op.drop_table('work_records')
    op.drop_index('uq_worker_company_phone', table_name='workers', postgresql_where=sa.text('phone IS NOT NULL'))
    op.drop_index('ix_workers_active', table_name='workers', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_table('workers')
    op.drop_index('ix_audit_logs_created_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
