"""add employee_number password_hash birth_date_8digits

Revision ID: ad1fa7eadb88
Revises: c3d4e5f6a7b8
Create Date: 2026-07-13 07:07:48.553853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1fa7eadb88'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_receiver_id', table_name='messages')
    op.drop_index('ix_messages_sender_id', table_name='messages')
    op.drop_index('ix_process_contracts_site_process', table_name='process_contracts')
    op.add_column('workers', sa.Column('employee_number', sa.String(length=50), nullable=True))
    op.add_column('workers', sa.Column('password_hash', sa.String(), nullable=True))
    op.alter_column('workers', 'birth_date',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=8),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workers', 'birth_date',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    op.drop_column('workers', 'password_hash')
    op.drop_column('workers', 'employee_number')
    op.create_index('ix_process_contracts_site_process', 'process_contracts', ['site_name', 'process'], unique=False)
    op.create_index('ix_messages_sender_id', 'messages', ['sender_id'], unique=False)
    op.create_index('ix_messages_receiver_id', 'messages', ['receiver_id'], unique=False)
    # ### end Alembic commands ###
