"""add_new_schema_gps_removed

Revision ID: d17d5aa61c72
Revises: 9614d542c65d
Create Date: 2026-07-10 00:59:49.429789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17d5aa61c72'
down_revision: Union[str, None] = '9614d542c65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('site', sa.String(length=100), nullable=True),
    sa.Column('process', sa.String(length=100), nullable=True),
    sa.Column('task', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.BigInteger(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('work_records', sa.Column('round', sa.Integer(), nullable=False))
    op.add_column('work_records', sa.Column('site_name', sa.String(length=100), nullable=False))
    op.add_column('work_records', sa.Column('shift_type', sa.String(length=10), nullable=False))
    op.add_column('work_records', sa.Column('note', sa.String(length=200), nullable=True))
    op.add_column('workers', sa.Column('role', sa.String(length=20), server_default='worker', nullable=False))
    op.add_column('workers', sa.Column('status', sa.String(length=20), server_default='입사예정', nullable=False))
    op.add_column('workers', sa.Column('work_status', sa.String(length=20), nullable=True))
    op.add_column('workers', sa.Column('team', sa.String(length=50), nullable=True))
    op.add_column('workers', sa.Column('group_name', sa.String(length=50), nullable=True))
    op.add_column('workers', sa.Column('squad', sa.String(length=20), nullable=True))
    op.add_column('workers', sa.Column('line', sa.String(length=50), nullable=True))
    op.add_column('workers', sa.Column('birth_date', sa.String(length=6), nullable=True))
    op.add_column('workers', sa.Column('resident_number_hash', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('expected_hire_date', sa.Date(), nullable=True))
    op.add_column('workers', sa.Column('blood_type', sa.String(length=5), nullable=True))
    op.add_column('workers', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('workers', sa.Column('job_title', sa.String(length=100), nullable=True))
    op.add_column('workers', sa.Column('profile_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'profile_image_url')
    op.drop_column('workers', 'job_title')
    op.drop_column('workers', 'gender')
    op.drop_column('workers', 'blood_type')
    op.drop_column('workers', 'expected_hire_date')
    op.drop_column('workers', 'resident_number_hash')
    op.drop_column('workers', 'birth_date')
    op.drop_column('workers', 'line')
    op.drop_column('workers', 'squad')
    op.drop_column('workers', 'group_name')
    op.drop_column('workers', 'team')
    op.drop_column('workers', 'work_status')
    op.drop_column('workers', 'status')
    op.drop_column('workers', 'role')
    op.drop_column('work_records', 'note')
    op.drop_column('work_records', 'shift_type')
    op.drop_column('work_records', 'site_name')
    op.drop_column('work_records', 'round')
    op.drop_table('worker_documents')
    op.drop_table('schedules')
    op.drop_table('sites')
    op.drop_table('notices')
    # ### end Alembic commands ###
